[project]
name = "rca-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.2.0",
    "langgraph-checkpoint-postgres>=2.0.0",
    "psycopg[binary]>=3.2.0",
    "langchain-openai>=0.3.0",
    "langchain>=0.3.0",
    "langchain-core>=0.3.0",
    "redis>=5.0.0",
    "pydantic>=2.0.0",
    "python-dotenv<=1.2.2",
    "playwright>=1.59.0",
    "pyppeteer>=0.0.25",
    "langchain-redis>=0.2.5",
    "langgraph-cli[inmem]>=0.4.26",
]
